import '../components/fixture-page/match.js';
import '../components/fixture-page/match-info.js';
import '../components/fixture-page/formation.js';
import '../components/fixture-page/lineup.js';
import '../components/fixture-page/statistic.js';
import '../components/fixture-page/odds.js';
import '../components/fixture-page/hhmatches.js';
import '../components/fixture-page/standings.js';
import '../components/fixture-page/mob-tabs.js';
